### ISSUE TITLE
Some dates have precision issues

### ISSUE THREAD

**Issue by AKAStarlord** [ishansingh2003/Alloy-Calendar-Widget#3]
![screen shot 2015-02-27 at 12 58 43 pm](https://cloud.githubusercontent.com/assets/11218414/6418132/8b88d870-be80-11e4-9b78-8adf865117d7.png)

As you can see some dates have impossible dates such as 30.958 etc.

**Comment by ishansingh2003** [comment]
thanks for identifying the issue. I will fix it soon.

**Comment by ishansingh2003** [comment]
Hi AKAStarlord,
I have checked the code and run it in the simulator, it working fine, that precision value was fixed long back, can you please pull the latest code and check. I am attaching a screenshot for your reference
![ios simulator screen shot 28-feb-2015 3 23 20 pm](https://cloud.githubusercontent.com/assets/5089525/6425737/ea57001e-bf5e-11e4-8fe7-8cbea5798997.png)
.
